# Minecraft 1.21
#
# Obfuscated (official mappings + intermediary), Java 21.
deps.minecraft=1.21
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=34

# Fabric
deps.fabric-loader=0.16.14
deps.fabric-api=0.102.0+1.21

# NeoForge
deps.neoforge=21.0.167

# Forge
deps.forge=51.0.33

# Publishing metadata
meta.minecraft-range=[1.21,1.21.1)
