# Minecraft 1.20.6
#
# Obfuscated (official mappings + intermediary), 21.
deps.minecraft=1.20.6
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=32

# Fabric
deps.fabric-loader=0.16.14
deps.fabric-api=0.100.8+1.20.6

# NeoForge
deps.neoforge=20.6.141

# Forge
deps.forge=50.2.10

# Publishing metadata
meta.minecraft-range=[1.20.6,1.20.7)
