# Minecraft 1.21.4
#
# Obfuscated (official mappings + intermediary), Java 21.
deps.minecraft=1.21.4
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=46

# Fabric
deps.fabric-loader=0.16.14
deps.fabric-api=0.119.4+1.21.4

# NeoForge
deps.neoforge=21.4.157

# Forge
deps.forge=54.1.18

# Publishing metadata
meta.minecraft-range=[1.21.4,1.21.5)
