# Minecraft 1.21.8
#
# Obfuscated (official mappings + intermediary), Java 21.
deps.minecraft=1.21.8
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=64

# Fabric
deps.fabric-loader=0.19.5
deps.fabric-api=0.136.1+1.21.8

# NeoForge
deps.neoforge=21.8.54

# Forge
deps.forge=58.1.22

# Publishing metadata
meta.minecraft-range=[1.21.8,1.21.9)
