# Minecraft 1.21.7
#
# Obfuscated (official mappings + intermediary), Java 21.
deps.minecraft=1.21.7
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=64

# Fabric
deps.fabric-loader=0.19.5
deps.fabric-api=0.129.0+1.21.7

# NeoForge
deps.neoforge=21.7.25-beta

# Forge
deps.forge=57.0.3

# Publishing metadata
meta.minecraft-range=[1.21.7,1.21.8)
