# Minecraft 1.21.6
#
# Obfuscated (official mappings + intermediary), Java 21.
deps.minecraft=1.21.6
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=63

# Fabric
deps.fabric-loader=0.19.5
deps.fabric-api=0.128.2+1.21.6

# NeoForge
deps.neoforge=21.6.20-beta

# Forge
deps.forge=56.0.9

# Publishing metadata
meta.minecraft-range=[1.21.6,1.21.7)
