# Minecraft 1.21.2
#
# Obfuscated (official mappings + intermediary), Java 21.
deps.minecraft=1.21.2
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=42

# Fabric
deps.fabric-loader=0.16.14
deps.fabric-api=0.106.1+1.21.2

# NeoForge
deps.neoforge=21.2.1-beta

# Forge
deps.forge=

# Publishing metadata
meta.minecraft-range=[1.21.2,1.21.3)
