# Minecraft 1.20.5
#
# Obfuscated (official mappings + intermediary), 21.
deps.minecraft=1.20.5
deps.java=21
deps.mixin-compat=JAVA_21
deps.pack-format=32

# Fabric
deps.fabric-loader=0.16.14
deps.fabric-api=0.97.8+1.20.5

# NeoForge
deps.neoforge=20.5.21-beta

# Forge
deps.forge=

# Publishing metadata
meta.minecraft-range=[1.20.5,1.20.6)
